---
driver:
  name: ec2
  require_chef_omnibus: 12.14.60
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  interface: public
  tags:
    Env: public
    Type: test

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04
    driver:
      tags:
        Name: default-et-storm-ubuntu-1404

suites:
- name: default
  run_list:
  - recipe[apt]
  - recipe[et_tools]
  - recipe[test_env::default]
  - recipe[et_storm::supervisor]
  - recipe[et_storm::nimbus]
