---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 1024

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  client_rb:
    environment: dev

platforms:
- name: ubuntu-14.04

suites:
- name: zookeeper1
  run_list:
  - recipe[apt]
  - recipe[et_zookeeper]
  - role[zookeeper]
  driver_config:
    network:
    - - private_network
      - ip: 192.168.33.10
  attributes:
    exhibitor:
      opts:
        configtype: file
- name: supervisor
  run_list:
  - recipe[apt]
  - recipe[et_tools]
  - recipe[et_storm::supervisor]
  driver_config:
    network:
    - - private_network
      - ip: 192.168.33.12
- name: nimbus
  run_list:
  - recipe[apt]
  - recipe[et_hostname]
  - recipe[et_tools]
  - recipe[et_storm::nimbus]
  driver_config:
    network:
    - - private_network
      - ip: 192.168.33.11
  attributes:
    et_hostname:
      addl_hosts_entries:
      - 192.168.33.11 dev-storm-nimbus-1b.priv.evertrue.com dev-storm-nimbus-1b
      - 192.168.33.10 dev-zookeeper-1b.priv.evertrue.com dev-zookeeper 1b
      - 192.168.33.12 dev-storm-supervisor-1b.priv.evertrue.com dev-storm-supervisor-1b
