name             'et_storm'
maintainer       'EverTrue, Inc.'
maintainer_email 'eric.herot@evertrue.com'
license          'All rights reserved'
description      'Installs/Configures et_storm'
long_description 'Installs/Configures et_storm'
version          '2.0.4'

depends 'apache_storm', '= 4.0.1'
depends 'et_swap', '~> 1.0'
depends 'sudo',  '~> 2.7'
