#!/usr/bin/env bash

search="${1}"
url='http://localhost:8080/api/v1/topology/summary'

if [ -n "$search" ]; then
  curl -s "${url}" | jq .topologies[].name | grep "^\"${search}\"$"
  exit $?
else
  curl -s "${url}" | jq .topologies[].name
fi
